name: app_truco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/background.jpg
    - images/truco.png
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icone_troco.png"
  android: true
  ios: true